### ISSUE TITLE
GroupMe 304 Handling Generates Fatal TypeError

### ISSUE THREAD

**Issue by sbonds** [rhgrant10/Groupy#20] opened 2016-03-16 22:51 UTC
While downloading all the messages in a group via `messages.iolder()`, when it hits the end of the group and GroupMe returns the expected 304 response, this ultimately triggers a fatal TypeError.

My current workaround is to catch and ignore those TypeErrors, but that's not quite optimal.

Here's some demonstration code similar to what's in the documentation:

````
#!/usr/bin/env python

# Test the messages.iolder() method which gives me these sorts of errors:
# File "/home/groupme/lib/python3.5/site-packages/groupy/object/responses.py", line 129, in messages
#     if e.args[0]['code'] == status.NOT_MODIFIED:
# TypeError: 'Response' object is not subscriptable

from groupy import Group

group = Group.list().first
print("Messages in group: %s" % (group.message_count))
messages = group.messages()
while messages.iolder():
        print("Messages downloaded: %s" % len(messages))
```

When run, the above eventually produces this traceback:

```
Traceback (most recent call last):
  File "/home/groupme/lib/python3.5/site-packages/groupy/api/endpoint.py", line 69, in response
    data = r.json()
  File "/home/groupme/lib/python3.5/site-packages/requests/models.py", line 763, in json
    return json.loads(self.text, **kwargs)
  File "/home/groupme/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/home/groupme/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/groupme/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/groupme/lib/python3.5/site-packages/groupy/object/responses.py", line 126, in messages
    since_id=since, after_id=after)
  File "/home/groupme/lib/python3.5/site-packages/groupy/api/endpoint.py", line 303, in index
    return cls.response(r)
  File "/home/groupme/lib/python3.5/site-packages/groupy/api/endpoint.py", line 71, in response
    raise errors.ApiError(r)
groupy.api.errors.ApiError: <Response [304]>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_iolder.py", line 13, in <module>
    while messages.iolder():
  File "/home/groupme/lib/python3.5/site-packages/groupy/object/listers.py", line 168, in iolder
    old = self.older()
  File "/home/groupme/lib/python3.5/site-packages/groupy/object/listers.py", line 145, in older
    return self.group.messages(before=self.oldest.id)
  File "/home/groupme/lib/python3.5/site-packages/groupy/object/responses.py", line 131, in messages
    if e.args[0]['code'] == status.NOT_MODIFIED:
TypeError: 'Response' object is not subscriptable
```

The problem seems to be that "e" is of type ApiError and doesn't appear to have a 'code' index available.

**Comment by mmirate** [comment] 2016-03-27 15:53
More precisely, `e.args[0]` is a Response object from the requests library, and that object does not seem dict-like at all. Rather, it has a `status_code` attribute.

As such, modifying the offending line such that it now reads `if e.args[0].status_code == status.NOT_MODIFIED:`, seems to fix the problem.

**Comment by mmirate** [comment] 2016-03-28 20:58
Hmm. Even more precisely, the nature of the argument of an `errors.ApiError` varies depending on whether the response body was valid JSON; if it didn't (which is the case with these 304's), then it contains the offending `requests.Response` object, else it contains the dictionary decoded from the relevant parts of the response body JSON. Looking through `groupme.object.responses`, most of the catch-blocks seem to assume that they will receive one particular type of ApiError (either a Response object or a dictionary).

**Comment by mmirate** [comment] 2016-04-14 16:05
Hmm, it appears this issue is a duplicate of #23.

**Closed** 2016-04-23 16:02 UTC
